---
- hosts: all
  vars:
    stat: "none"
  tasks:
    - name: Set Flag
      command: /home/ec2-user/democontol.sh "{{ stat }}" disable    
 
    - name: Log 1
      debug:
        msg: "{{ stat }}"
